### ISSUE TITLE
stopped working with framabag.org

### ISSUE THREAD

**Issue by inside83** [wallabag/wallabagger#191] opened 2020-01-29 08:57 UTC
Newsest verion of the extension (1.9.1) doesn't seam to work with framabag.org (API version 2.3).
It loads it but doesn't get the token and can't save.

**Comment by Simounet** [comment] 2020-01-29 16:24
Hi,
I'm sorry to ear that. Was it working previously? Which browser (and version) is it? Do you have any extension that can block the call?

**Comment by abjoseph** [comment] 2020-01-30 11:56
@Simounet Hi, I'm another user and I can confirm that there was a regression in the latest version 1.9.0 (1.9.1 as shown in chrome store). It was working previously in versions 1.8.0 and 1.7.0, which I installed for verification using the method detailed in **Installation** instructions at this [link](https://rurik19.github.io/wallabagger/installation). 

The versions for 1.8.0 and 1.7.0 were acquired from the source code links below:

1.8.0 - [Source Code with *.manifest file](https://github.com/wallabag/wallabagger/archive/v1.8.0.zip)
1.7.0 - [Source Code with *.manifest file](https://github.com/wallabag/wallabagger/archive/v1.7.0.zip)

**Comment by tcitworld** [comment] 2020-01-30 12:45
cc @Rurik19 for Chrome Store publishing.

**Comment by Simounet** [comment] 2020-01-30 13:22
Thank for such a precious user reply! We will investigate it as soon as possible. Can you confirm it is a Chrome issue for you too @inside83?

**Comment by Rurik19** [comment] 2020-01-30 16:07
The story is:
chrome webtsore refuse publishing wallabagger 1.9.0 with permission ""*://*/",", because of "security". I did so, checked in various browsers|OS on app.wallabag.it, and published.
And for framabag.org we have this old error:
`Access to fetch at 'https://framabag.org/api/version' from origin 'chrome-extension://cmkfljnmbpklhocepmmcfchkeiejjenp' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.` 

I can add "https://framabag.org" to permissions and publish 1.9.2, but what about selfhosted apps?
maybe we should check CORS settings in framabag.org?

**Comment by Rurik19** [comment] 2020-01-30 16:57
it seems that with "*://*/api/" in permissions all works, i'll try to publish that tomorrow

**Comment by Rurik19** [comment] 2020-01-31 11:18
published again, but now it is on the approving

**Comment by inside83** [comment] 2020-01-31 20:50
> Thank for such a precious user reply! We will investigate it as soon as possible. Can you confirm it is a Chrome issue for you too @inside83?

I installed WallabagIt (https://chrome.google.com/webstore/detail/wallabagit/peehlcgckcnclnjlndmoddifcicdnabm) and it works on framabag.org but not as convenient as this addon.

**Comment by abjoseph** [comment] 2020-02-01 17:49
@Rurik19 @Simounet I can confirm that the new Chrome store version: 1.9.2 is working as expected against self-hosted version: 2.3.8 of Wallabag. Thanks again to everyone for such as quick turn-around.

**Comment by Rurik19** [comment] 2020-02-02 04:51
**inside83** Check v1.9.2 please

**Comment by ojob** [comment] 2020-02-03 07:49
Works for me! Thanks a lot, and congratulations, for this quick update 👍

**Comment by tcitworld** [comment] 2020-02-03 10:58
Closing then, thank you all.

**Closed by tcitworld** 2020-02-03 10:58 UTC
Labels: bug
